[package]
name = "bot_config"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
toml = "0.5"

[dependencies.serde]
version = "1.0"
features = ["derive"]
